# These are supported funding model platforms

github: # OpenRecorder, OpenRecorderStudio, ORS, OpenRec.
patreon: # OpenRecorder Studio (Coming Soon)
custom: # pronnerstudios.com/openrecorder-studio (Coming Soon)
